### PR TITLE
Docs: Duplicate port warning.

### PR DESCRIPTION
**Pull request by nitrag**
Notate that duplicate ports are not allowed.

### CODE REVIEW

**Comment by alejandrox1** [comment]
Hi @nitrag thank you for raising this issue.
before anything else: you should sign the CLA so you can contribute to Kubernetes projects :smile: 

follow up question: why did you consider the warning was necessary?

**Comment by M00nF1sh** [comment]
Hi, @nitrag 
Thanks for contributing.
I think Jorge's point is good...i don't think this worth an warning as well :D...

**Comment by nitrag** [comment]
My use case was forwarding **either** HTTP or HTTPS, which is an AWS limitation.

Without any log errors or a note in the docs I didn't realize that was the problem with my configuration and only realized my error when trying to make the change in the AWS dashboard and it showed me the error there. I figured adding the warning could save someone 1-2 hours troubleshooting in the future.

**Comment by bhagwat070919** [comment]
Hi,

I like the idea of providing enough information about the failure and saving developer's time.

**Pull request merged**
