### PR TITLE
Add documentation about configuring WAF

### PR DESCRIPTION
**Pull request by vladimirmukhin**
This is to address the following two issues:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/608
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/883

Included WAF annotations into the documentation.

### CODE REVIEW

**Comment by vladimirmukhin** [comment]
@bigkraig @M00nF1sh Are you guys planning to take a look at this?

**Comment by M00nF1sh** [comment]
@vladimirmukhin Hi, thanks so much for fix this missing doc. sorry for the late reply, i missed this PR.

**Pull request merged**
