### PR TITLE
Added configuration page for ALB Ingress Controller with Cognito auth.

### PR DESCRIPTION
**Pull request by procyclinsur**
### Requirement:  

Cognito + ALB Integration has been implemented in code #754, and an ingress template has been created #875 but there is no documentation on minimal setup of the infrastructure required.

**This PR:**

- [x] Created documentation describing a minimal setup of infrastructure for ALB Ingress Controller + Cognito integration.

### CODE REVIEW

**Comment by procyclinsur** [comment]
Unfortunately, I am unsure of how the site generator for the docs pages is working, is there any work needed at the site generation level to enable these pages?

**Comment by M00nF1sh** [comment]
@procyclinsur 
Thanks so much for fill the gap!!!
The docs needs to be linked in [this file](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/mkdocs.yml) to be available in live docs.
You can preview the docs using steps below:
1. install python3 & pipenv
2.  
```
pipenv install mkdocs
pipenv install mkdocs-material 
make  docs-serve
``` 
3. open http://127.0.0.1:8000

**Comment by procyclinsur** [comment]
@M00nF1sh Thanks for the guidance on linking the page to the docs.   Seems to be working!

Let me know if there is anything else missing.

**Pull request merged**
