### PR TITLE
#797 Add a forward actions annotation to allow forwarding to external target groups

### PR DESCRIPTION
**Pull request by gigi-at-zymergen**
@M00nF1sh made a simple and elegant suggestion for how to implement a solution for a use case I outlined in https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/797 . This PR attempts to follow the guidance in that issue. I have locally run `make test` and `make lint` successfully. 

I've signed the CLA as an individual, but have been working on this as part of my day job at Zymergen, and am working with our legal department to get our company to sign and add me as an authorized contributor. I don't anticipate any snags, but probably should hold off on merging.

* Added a new case statement to allow for actions annotations of type `forward`
* Added a new docs/guide/tasks/migrate_legacy_apps.md to document the use case an present an example of how to use it
* Added a dummy forward annotation to the unit test, which should assure happy path, but would be up for suggestions on other good assertions.

### CODE REVIEW

**Comment by M00nF1sh** [comment]
Thanks so much for support this, nice documentation 👍 .
I think you are right, we should hold this until your company's legal team approves the contribution 😄
(Code and documentation LGTM 😄 )
/ok-to-test
/hold

**Comment by gigi-at-zymergen** [comment]
@M00nF1sh Zymergen legal has now signed, and I have joined the Zymergen CNCF group as an authorized contributer, so we are good to remove the hold from a legal perspective. Thanks for all your help!

**Comment by manushi-bcsn** [comment]
I have added a below annotations in my ingress file.

alb.ingress.kubernetes.io/actions.forward-tg: |
      {"type":"forward","targetGroupARN":"ARN of target group"}

Also I have used it in ingress spec.
spec:
  rules:
  - host: abc.com
    http:
      paths:
      - backend:
          service:
            name: forward-tg
            port:
              name: use-annotation
        path: /bmw
        pathType: Prefix

But it is showing error like as below:

error: forward-tg:use-annotation (<error: endpoints "forward-tg" not found>)

Just to add ALB and my EC2 both are in same VPC and also EC2 is in public subnet.
I have checked to add rule manually in ALB and it is working properly.

I don't know what's the issue with ingress that it could not find my target group ARN.

Can anyone please help me with this?

**Pull request merged**
