### PR TITLE
Added docs for creating DNS pointing from ingress object

### PR DESCRIPTION
**Pull request by luvpreetsingh**
### Description:
Added docs for creating DNS pointing from ingress object

### Motivation:
I had set up the external-dns but I was having trouble finding the docs on how to add the dns entry using ingress/service/external-dns for a particular service in kubernetes. I then had to go through a lot of blogs/articles and at one place I finally found that it can be done using annotations. I think that it should be described in the docs that after setting up the external-dns how one can use it to create dns record-sets for their apps. Maybe I didn't look thoroughly enough, if so, please point in the right direction :) Also, please excuse any English grammar mistakes, if any, it's not my first language.

### Testing:
I did not do any testing as it was only documentation changes.

### CODE REVIEW

**Comment by M00nF1sh** [comment]
Thanks so much for making contributions 🚀

**Comment by luvpreetsingh** [comment]
can someone please help with this failed test? I have no idea of it whatsoever.

**Comment by luvpreetsingh** [comment]
@M00nF1sh can it be merged if you approve of this?

**Pull request merged**
