### PR TITLE
cut v1.0.0 release

### PR DESCRIPTION
**Pull request by M00nF1sh**
1. Cutting v1.0.0 release(we decided to change to use semantic version to align with go community)
2. Change default force sync time to 60 minutes(from 30 seconds)

### CODE REVIEW

**Comment by rifelpet** [comment]
@M00nF1sh can we include the docker image in the Release assets?

**Comment by M00nF1sh** [comment]
@rifelpet 
nice suggestion!  do you mean adding links to release note(like quay.io/coreos/alb-ingress-controller:v1.0.0), or attach the image as a file? 😄

**Comment by M00nF1sh** [comment]
We can host our image in ECR, but currently there is an accountID in ECR endpoints 😞 .

Instead I have started an internal process to able to host our image in https://hub.docker.com/u/amazon/

**Pull request merged**
