### PR TITLE
Expose aws security policy attribute

### LINKED ISSUE #201: Expose AWS Security Policy attribute
Would be great to expose this attribute during ALB creation as the default SSL Policy doesn't meet PCI DSS standards.http://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies

### PR DESCRIPTION
**Pull request by feltraco**
Fix #201 
I have not created any tests, and unfortunately I will not be able to add any in the near term.

### CODE REVIEW

**Comment by bigkraig** [comment]
@feltraco Can you sign the CLA?

**Comment by bigkraig** [comment]
@feltraco and if you can please also follow these instructions so i can add some commits to the PR? https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by lareeth** [comment]
@feltraco I was meaning to create a pull request for this change, which I created a week or so back here https://github.com/lareeth/aws-alb-ingress-controller/tree/feature-ssl-policy

Are you still having issues signing the CLA, would you be OK if I submitted a pull request instead?

**Comment by feltraco** [comment]
Hi @lareeth , please go ahead and create the pull request.
Thank you!

**Pull request closed without merging**
