### PR TITLE
build to quay.io

### PR DESCRIPTION
**Pull request by M00nF1sh**
Build to quay.io again since ECR images cannot be pulled in Prow cluster :( 

See https://github.com/helm/charts/pull/9813

### CODE REVIEW

**Comment by M00nF1sh** [comment]
> @M00nF1sh - why not internal docker hub?

It's not ready yet..i'll try ping Samuel to see whether he can do it today, the distribution have been approved

**Comment by d-nishi** [comment]
That’s preferred yes.

**Comment by M00nF1sh** [comment]
closing this since i'll get the dockerhub account today 😄

**Comment by d-nishi** [comment]
👍

**Pull request closed without merging**
