### PR TITLE
Walkthrough egrep quotes amended + readability

### PR DESCRIPTION
**Pull request by vincentjorgensen**
Minor edits for usability and readability of the walkthrough.

### CODE REVIEW

**Comment by M00nF1sh** [comment]
/lgtm
I'll take some time to fix travil, since some go module stuff breaks it

**Comment by M00nF1sh** [comment]
@vincentjorgensen 
Hi, the build problem have been fixed.
i guess you have to close & reopen this pr to trigger travis again 😸

**Comment by vincentjorgensen** [comment]
I recommited to get Travis to pick it up again. Sorry for the extra commit "Merge" message.

**Pull request merged**
