### PR TITLE
Tagging and naming restructuring

### LINKED ISSUE #426: Delete loadbalancer resources in existing, separated Kubernetes cluster after deployment
We have a running Kuberntes cluster in the same AWS account, with alb-ingress-controller controlled ingresses. This name is "test-cluster.internal".

When a new Kubernetes cluster started, with name "live-cluster.internal", when the alb-ingress-controller deployed, it DELETES the already existing loadbalancers and target groups.

It started and immediately delete the anoter cluster's existing resource:
```
ubuntu@ip-10-202-13-63:~$ kubectl logs alb-ingress-controller-69c9b847c5-vqfzg -n kube-system
I0626 16:00:37.571370       1 main.go:24] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0626 16:00:37.571721       1 launch.go:112] &{ALB Ingress Controller 1.0-alpha.9 git-11cdb4a8 git://github.com/kubernetes-sigs/aws-alb-ingress-controller}
I0626 16:00:37.571875       1 launch.go:282] Creating API client for https://100.64.0.1:443
I0626 16:00:37.583242       1 launch.go:295] Running in Kubernetes Cluster version v1.9 (v1.9.6) - git (clean) commit 9f8ebd171479bec0ada837d7ee641dec2f8c6dd1 - platform linux/amd64
I0626 16:00:37.585281       1 launch.go:134] validated kube-system/default-http-backend as the default backend
I0626 16:00:37.589904       1 albingresses.go:85] [ALB-INGRESS] [ingress] [INFO]: Building list of existing ALBs
I0626 16:00:37.683768       1 albingresses.go:94] [ALB-INGRESS] [ingress] [INFO]: Fetching information on 1 ALBs
I0626 16:00:38.011262       1 targetgroups.go:103] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Fetching Targets for Target Group arn:aws:elasticloadbalancing:eu-west-1:571188843450:targetgroup/bmkubernete-30658-HTTP-2a53f87/1289759a5fc2d701
I0626 16:00:38.067303       1 targetgroups.go:103] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Fetching Targets for Target Group arn:aws:elasticloadbalancing:eu-west-1:571188843450:targetgroup/bmkubernete-31364-HTTP-2a53f87/29a6840f649f5b2a
I0626 16:00:38.135349       1 targetgroups.go:103] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Fetching Targets for Target Group arn:aws:elasticloadbalancing:eu-west-1:571188843450:targetgroup/bmkubernete-32497-HTTP-2a53f87/8eb65e30b9173cb6
I0626 16:00:38.187385       1 listeners.go:77] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Fetching Rules for Listener arn:aws:elasticloadbalancing:eu-west-1:571188843450:listener/app/bmkubernete-default-bmtest-7639/5a10c9cf5756d3c3/9553958eb47b7f69
I0626 16:00:38.203338       1 albingress.go:203] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Ingress rebuilt from existing ALB in AWS
I0626 16:00:38.203371       1 albingresses.go:189] [ALB-INGRESS] [ingress] [INFO]: Assembled 1 ingresses from existing AWS resources in 613.445553ms
I0626 16:00:38.203408       1 controller.go:1359] starting Ingress controller
I0626 16:00:38.630484       1 leaderelection.go:174] attempting to acquire leader lease...
I0626 16:00:38.630771       1 controller.go:477] backend reload required
I0626 16:00:38.630831       1 loadbalancer.go:230] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Start ELBV2 (ALB) deletion.
I0626 16:00:38.637249       1 leaderelection.go:184] successfully acquired lease kube-system/ingress-controller-leader-alb
I0626 16:00:38.637298       1 status.go:193] new leader elected: alb-ingress-controller-69c9b847c5-vqfzg
I0626 16:00:38.683627       1 loadbalancer.go:238] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Completed ELBV2 (ALB) deletion. Name: bmkubernete-default-bmtest-7639 | ARN: arn:aws:elasticloadbalancing:eu-west-1:571188843450:loadbalancer/app/bmkubernete-default-bmtest-7639/5a10c9cf5756d3c3
I0626 16:00:38.683650       1 listener.go:74] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Start Listener deletion.
I0626 16:00:38.693789       1 listener.go:79] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Completed Listener deletion.
I0626 16:00:38.693869       1 rule.go:96] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Start Rule deletion.
I0626 16:00:38.730221       1 rule.go:103] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Completed Rule deletion. Rule Priority: "1" | Condition: [{    Field: "host-header",    Values: ["wwwwww"]  },{    Field: "path-pattern",    Values: ["/*"]  }]
I0626 16:00:38.730242       1 rule.go:96] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Start Rule deletion.
I0626 16:00:38.772282       1 rule.go:103] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Completed Rule deletion. Rule Priority: "2" | Condition: [{    Field: "path-pattern",    Values: ["/*"]  },{    Field: "host-header",    Values: ["wwwwwwwwww"]  }]
I0626 16:00:38.772307       1 rule.go:96] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Start Rule deletion.
I0626 16:00:38.793698       1 rule.go:103] [ALB-INGRESS] [default/bm-test-ingress] [INFO]: Completed Rule deletion. Rule Priority: "3" | Condition: [{    Field: "path-pattern",    Values: ["/*"]  },{    Field: "host-header",    Values: ["wwwwwwwww"]  }]
I0626 16:00:49.006933       1 controller.go:486] ingress backend successfully reloaded...

```

It shouldn't touch other, already existing resources!

### PR DESCRIPTION
**Pull request by bigkraig**
This PR creates an `albNamePrefix` parameter which can be different than the cluster name. This allows the AWS resources to have a different prefix, which allows longer more Kubernetes standard cluster names.

If the prefix is undefined, it will fall back to the existing clustername truncation logic.

This also changes how we match load balancers in AWS, using the `kubernetes.io/cluster/<cluster name>` tagging convention, removing the naming convention requirement.

Resolves #426

### CODE REVIEW

**Comment by tatobi** [comment]
@bigkraig, I'd like to suggest a consistent solution to keep backward compatibility as well and solve the very risky problem caused by 11+ cluster name truncation. 
It would be easy to use CRC32 of the whole cluster name istead of just a name-cut prefix. The CRC32 string output is 8bytes long, so it fits in the 11 char limit of current logic. (we have 3 more digits to append from thw original name). It can be used together the above perfect solution as a fallback method.

**Comment by bigkraig** [comment]
@tatobi LMK

**Comment by tatobi** [comment]
@bigkraig , thank you. I'm checking it now.

**Comment by tatobi** [comment]
I've built it and pushed the image to my registry in ECR. It seems it is working fine, with a few comments:
Because it is using the hashing method, the old, 11char name-cut version LB remained on-place. BUT it is fine that it replaced semlessly the old Route53 ALIAS record with the new ELBv2 one semaplessly! Using together with dns-controller plugin is a good combination.
The only thing is after update, the old one should be removed by hand: LB and TGs.

I can see in the logs peridically:
```alb-controller.go:149] [ALB-INGRESS] [controller] [INFO]: Ingress update being attempted. (Forced from no event seen in 60 second session.go:35] [ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/DescribeTargetHealth, Payload: {  TargetGroupArn: "arn:aws:elasticloadbalancing:eu-west-1:571188843450:targetgroup/683e1275-31364-HTTP-f2a3a9c/62cd952eaa8b6474",  Targets: [{      Id: "i-0041f252df07b9cdd",      Port: 31364    },{      Id: "i-0625aa9e9a68950e6",      Port: 31364    },{      Id: "i-07e9b93892077f5e6",      Port: 31364    }]}
I0627 07:42:35.631691       1 session.go:35] [ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/DescribeTargetHealth, Payload: {  TargetGroupArn: "arn:aws:elasticloadbalancing:eu-west-1:571188843450:targetgroup/683e1275-30658-HTTP-f2a3a9c/443a3e13f97773e0",  Targets: [{      Id: "i-0041f252df07b9cdd",      Port: 30658    },{      Id: "i-0625aa9e9a68950e6",      Port: 30658    },{      Id: "i-07e9b93892077f5e6",      Port: 30658    }]}
I0627 07:42:35.657266       1 session.go:35] [ALB-INGRESS] [session] [INFO]: Request: elasticloadbalancing/DescribeTargetHealth, Payload: {  TargetGroupArn: "arn:aws:elasticloadbalancing:eu-west-1:571188843450:targetgroup/683e1275-32497-HTTP-f2a3a9c/7b6e0fab30b383a2",  Targets: [{      Id: "i-0041f252df07b9cdd",      Port: 32497    },{      Id: "i-0625aa9e9a68950e6",      Port: 32497    },{      Id: "i-07e9b93892077f5e6",      Port: 32497    }]}```

Does that mean anything but check internal state / AWS state?

Thank you!

**Comment by tatobi** [comment]
I've deployed two clusters, new image, same setup like yesterday. It looks like working well.
Thank you much!

**Pull request merged**
