### PR TITLE
Optionally apply default tags to all resources.

### LINKED ISSUE #187: Allow default set of AWS Tags to be specified on the controller
[enhancement]
It would be convenient if I could specify a default set of Tags on the controller, such that all ALBs it creates would be given those tags (some of which might be overridden by an individual Ingress object's annotations).

### PR DESCRIPTION
**Pull request by jmcarp**
If the approach makes sense, I'll add tests and docs.

[Fixes #187]

### CODE REVIEW

**Comment by bigkraig** [comment]
:+1: this looks like a good approach to me

**Comment by M00nF1sh** [comment]
👍 looks good to me too.(we can add support to tag securityGroup in similar way)

**Comment by M00nF1sh** [comment]
@jmcarp 
Hi, this changes looks good to me, would you help adding some tests and docs, so we can merge this 👍

**Comment by jmcarp** [comment]
Added tests and docs.

**Comment by M00nF1sh** [comment]
/lgtm
Thanks for make this contribution 👍

**Pull request merged**
