### PR TITLE
Add missing permission

### PR DESCRIPTION
**Pull request by dokipen**
Adds permission for ingress-controller to add security groups to interfaces.

### CODE REVIEW

**Comment by M00nF1sh** [comment]
Thanks for make this change, lgtm 👍 
could you sign the CLA so we can merge this?

**Comment by dokipen** [comment]
I signed it, will the check auto-rerun?

**Comment by M00nF1sh** [comment]
/lgtm
/approve

I guess it should be automatically re-check the cla somehow :D

**Comment by bigkraig** [comment]
@dokipen Try a comment with just "I signed it" 

from: https://identity.linuxfoundation.org/projects/cncf

**Comment by dokipen** [comment]
I signed it

**Pull request closed without merging**
