### PR TITLE
optimize endpoint reconcile

### PR DESCRIPTION
**Pull request by OmerKahani**
Checks if the endpoint is of a service that the ingress serve
related to #1103 #1163

### CODE REVIEW

**Comment by OmerKahani** [comment]
@m00nf1sh Hi, I want to add this check, we had a problem where unrelated pod triggers a lot of reconciles, resulting in API Request Throttling. 
before I start with implementing the check, do you think this is the right place to put the function?

**Comment by M00nF1sh** [comment]
Hi thanks for taking this 🤣.
i think the check can just be put inside the `EnqueueRequestsForEndpointsEvent` file.

**Comment by OmerKahani** [comment]
There is a typo in the branch name :(
closing this PR in favor for #1179 (same code)

**Pull request closed without merging**
