### PR TITLE
Updated the ingress name.

### PR DESCRIPTION
**Pull request by tde908**
Updated the ingress name to reflect the ALB ingress controller.

### CODE REVIEW

**Comment by jaypipes** [comment]
Thanks! /lgtm

**Comment by tde908** [comment]
hi @jaypipes,
I don't believe that the tag for "lgtm" was picket up by the ci-robot. 

Cheers.

**Comment by M00nF1sh** [comment]
/lgtm
i think jay needs to be added to https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/OWNERS to work

**Pull request merged**
