### PR TITLE
fix(docs): Updated link to example iam-policy that was moved per #701.

### PR DESCRIPTION
**Pull request by cj-taylor**
Was following the walkthrough guide for configuration of kube2iam and found this link to be stale per #701.

### CODE REVIEW

**Comment by cj-taylor** [comment]
I signed it

**Comment by M00nF1sh** [comment]
@cj-taylor hi, did you sign the CLA using your email cj-taylor@outlook.com? 
=.=seems the CLA check still fails..

**Comment by cj-taylor** [comment]
@M00nF1sh, yeah, just went through the signing process again, it's via cj-taylor@outlook.com.

/check-cla

**Comment by M00nF1sh** [comment]
/lgtm
/approve

Thanks for fixing this 👍

**Pull request merged**
