### PR TITLE
Fixes #748

### LINKED ISSUE #748: Incorrect iam policy
The documented policy doesn't have:

"ec2:DescribeAccountAttributes"
"ec2:DescribeInternetGateways"
"iam:CreateServiceLinkedRole"

But, the controller needs them.

### PR DESCRIPTION
**Pull request by vincentheet**
Improved the policy example to include the needed permissions as described in issue #748

### CODE REVIEW

**Comment by M00nF1sh** [comment]
Thanks for fixing this， would you help add ec2:DescribeAddresses as it specified in https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/elb-api-permissions.html

**Comment by vincentheet** [comment]
Of course, added a commit to add ec2:DescribeAddresses.

**Pull request merged**
