### PR TITLE
Rewrite helm chart

### PR DESCRIPTION
**Pull request by M00nF1sh**
Changes done:
1. deprecate quay registry plugin
2. rewrite using helm 2.11.0
3. rename chart from `alb-ingress-controller-helm` into `aws-alb-ingress-controller`
4. move helm chart into deployments/charts/ according to https://github.com/golang-standards/project-layout
5. remove helm upload from travis(`make docs-deploy` will release it to github pages)

Test done:
Instructions in README.md and NOTEs.txt

Future work:
Merge this into central helm repo and remove the mkdocs-helm plugin.(only need to update instructions in README.md, nothing else should require changes)

### CODE REVIEW

**Comment by M00nF1sh** [comment]
@Jeeppler @rifelpet  I guess you both can be happy for now 😄  Only thing left is move it to central helm repo. (we can use our custom repo as an workaround).

**Comment by rifelpet** [comment]
Awesome! Based on https://github.com/helm/charts/pull/7236#issuecomment-438845107, now that the controller is stable (version 1.X), any reason we can't also move forward with getting the chart in the official helm repo?

**Comment by M00nF1sh** [comment]
> Awesome! Based on [helm/charts#7236 (comment)](https://github.com/helm/charts/pull/7236#issuecomment-438845107), now that the controller is stable (version 1.X), any reason we can't also move forward with getting the chart in the official helm repo?

i don't think there are any technical issue blocking us to do so...but i haven't managed find a helm guy willing to help... 😞

**Comment by Jeeppler** [comment]
@M00nF1sh did you reach out to the external DNS maintainers? Is anybody from Amazon AWS working working on that chart and can approve it?

@d-nishi Is there anybody else at Amazon AWS who has contributor access to Helm and could approve @M00nF1sh pull request?

**Pull request closed without merging**
