### PR TITLE
Syntax fixing on Verify the deployment

### PR DESCRIPTION
**Pull request by ziabs**

### CODE REVIEW

**Comment by M00nF1sh** [comment]
/ok-to-test
/approve 

Thanks for contributing 👍

**Comment by M00nF1sh** [comment]
@ziabs Hi， would you help sign the CLA so we can merge this?
TIP: you need to include your email(that you signed CLA with) as meta info in your commit.

**Comment by ziabs** [comment]
I signed it
info.ziabs@gmail.com

**Comment by ziabs** [comment]
I signed it
info.ziabs@gmail.com

**Comment by ziabs** [comment]
/I signed it
[info.ziabs@gmail.com](mailto:info.ziabs@gmail.com)

**Comment by ziabs** [comment]
cncf-cla: yes

**Comment by ziabs** [comment]
lgmt

**Comment by ziabs** [comment]
lgtm

**Comment by ziabs** [comment]
approved

**Comment by ziabs** [comment]
lgtm approved

**Comment by ziabs** [comment]
lgtm 
approved 
cncf-cla: yes

**Pull request merged**
